/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminWorkflowsRouteImport } from './routes/_authenticated/admin.workflows'
import { Route as AuthenticatedSettingsCatalogueRouteImport } from './routes/_authenticated/settings.catalogue'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedSettingsQuotationTemplateRouteImport } from './routes/_authenticated/settings.quotation-template'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedWorkbenchIntakeRouteImport } from './routes/_authenticated/workbench.intake'
import { Route as AuthenticatedWorkbenchPortfolioRouteImport } from './routes/_authenticated/workbench.portfolio'
import { Route as AuthenticatedWorkbenchPricingRouteImport } from './routes/_authenticated/workbench.pricing'
import { Route as AuthenticatedWorkbenchRequirementsRouteImport } from './routes/_authenticated/workbench.requirements'
import { Route as AuthenticatedWorkbenchReviewRouteImport } from './routes/_authenticated/workbench.review'
import { Route as AuthenticatedWorkbenchSourcingRouteImport } from './routes/_authenticated/workbench.sourcing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminWorkflowsRoute =
  AuthenticatedAdminWorkflowsRouteImport.update({
    id: '/admin/workflows',
    path: '/admin/workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCatalogueRoute =
  AuthenticatedSettingsCatalogueRouteImport.update({
    id: '/settings/catalogue',
    path: '/settings/catalogue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsQuotationTemplateRoute =
  AuthenticatedSettingsQuotationTemplateRouteImport.update({
    id: '/settings/quotation-template',
    path: '/settings/quotation-template',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchIntakeRoute =
  AuthenticatedWorkbenchIntakeRouteImport.update({
    id: '/workbench/intake',
    path: '/workbench/intake',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchPortfolioRoute =
  AuthenticatedWorkbenchPortfolioRouteImport.update({
    id: '/workbench/portfolio',
    path: '/workbench/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchPricingRoute =
  AuthenticatedWorkbenchPricingRouteImport.update({
    id: '/workbench/pricing',
    path: '/workbench/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchRequirementsRoute =
  AuthenticatedWorkbenchRequirementsRouteImport.update({
    id: '/workbench/requirements',
    path: '/workbench/requirements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchReviewRoute =
  AuthenticatedWorkbenchReviewRouteImport.update({
    id: '/workbench/review',
    path: '/workbench/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchSourcingRoute =
  AuthenticatedWorkbenchSourcingRouteImport.update({
    id: '/workbench/sourcing',
    path: '/workbench/sourcing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/settings/catalogue': typeof AuthenticatedSettingsCatalogueRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/quotation-template': typeof AuthenticatedSettingsQuotationTemplateRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/workbench/intake': typeof AuthenticatedWorkbenchIntakeRoute
  '/workbench/portfolio': typeof AuthenticatedWorkbenchPortfolioRoute
  '/workbench/pricing': typeof AuthenticatedWorkbenchPricingRoute
  '/workbench/requirements': typeof AuthenticatedWorkbenchRequirementsRoute
  '/workbench/review': typeof AuthenticatedWorkbenchReviewRoute
  '/workbench/sourcing': typeof AuthenticatedWorkbenchSourcingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/settings/catalogue': typeof AuthenticatedSettingsCatalogueRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/quotation-template': typeof AuthenticatedSettingsQuotationTemplateRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/workbench/intake': typeof AuthenticatedWorkbenchIntakeRoute
  '/workbench/portfolio': typeof AuthenticatedWorkbenchPortfolioRoute
  '/workbench/pricing': typeof AuthenticatedWorkbenchPricingRoute
  '/workbench/requirements': typeof AuthenticatedWorkbenchRequirementsRoute
  '/workbench/review': typeof AuthenticatedWorkbenchReviewRoute
  '/workbench/sourcing': typeof AuthenticatedWorkbenchSourcingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/_authenticated/settings/catalogue': typeof AuthenticatedSettingsCatalogueRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/quotation-template': typeof AuthenticatedSettingsQuotationTemplateRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/workbench/intake': typeof AuthenticatedWorkbenchIntakeRoute
  '/_authenticated/workbench/portfolio': typeof AuthenticatedWorkbenchPortfolioRoute
  '/_authenticated/workbench/pricing': typeof AuthenticatedWorkbenchPricingRoute
  '/_authenticated/workbench/requirements': typeof AuthenticatedWorkbenchRequirementsRoute
  '/_authenticated/workbench/review': typeof AuthenticatedWorkbenchReviewRoute
  '/_authenticated/workbench/sourcing': typeof AuthenticatedWorkbenchSourcingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/workflows'
    | '/settings/catalogue'
    | '/settings/company'
    | '/settings/quotation-template'
    | '/settings/users'
    | '/workbench/intake'
    | '/workbench/portfolio'
    | '/workbench/pricing'
    | '/workbench/requirements'
    | '/workbench/review'
    | '/workbench/sourcing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/workflows'
    | '/settings/catalogue'
    | '/settings/company'
    | '/settings/quotation-template'
    | '/settings/users'
    | '/workbench/intake'
    | '/workbench/portfolio'
    | '/workbench/pricing'
    | '/workbench/requirements'
    | '/workbench/review'
    | '/workbench/sourcing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/approvals'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/workflows'
    | '/_authenticated/settings/catalogue'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/quotation-template'
    | '/_authenticated/settings/users'
    | '/_authenticated/workbench/intake'
    | '/_authenticated/workbench/portfolio'
    | '/_authenticated/workbench/pricing'
    | '/_authenticated/workbench/requirements'
    | '/_authenticated/workbench/review'
    | '/_authenticated/workbench/sourcing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/workflows': {
      id: '/_authenticated/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/catalogue': {
      id: '/_authenticated/settings/catalogue'
      path: '/settings/catalogue'
      fullPath: '/settings/catalogue'
      preLoaderRoute: typeof AuthenticatedSettingsCatalogueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/quotation-template': {
      id: '/_authenticated/settings/quotation-template'
      path: '/settings/quotation-template'
      fullPath: '/settings/quotation-template'
      preLoaderRoute: typeof AuthenticatedSettingsQuotationTemplateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/intake': {
      id: '/_authenticated/workbench/intake'
      path: '/workbench/intake'
      fullPath: '/workbench/intake'
      preLoaderRoute: typeof AuthenticatedWorkbenchIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/portfolio': {
      id: '/_authenticated/workbench/portfolio'
      path: '/workbench/portfolio'
      fullPath: '/workbench/portfolio'
      preLoaderRoute: typeof AuthenticatedWorkbenchPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/pricing': {
      id: '/_authenticated/workbench/pricing'
      path: '/workbench/pricing'
      fullPath: '/workbench/pricing'
      preLoaderRoute: typeof AuthenticatedWorkbenchPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/requirements': {
      id: '/_authenticated/workbench/requirements'
      path: '/workbench/requirements'
      fullPath: '/workbench/requirements'
      preLoaderRoute: typeof AuthenticatedWorkbenchRequirementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/review': {
      id: '/_authenticated/workbench/review'
      path: '/workbench/review'
      fullPath: '/workbench/review'
      preLoaderRoute: typeof AuthenticatedWorkbenchReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/sourcing': {
      id: '/_authenticated/workbench/sourcing'
      path: '/workbench/sourcing'
      fullPath: '/workbench/sourcing'
      preLoaderRoute: typeof AuthenticatedWorkbenchSourcingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminWorkflowsRoute: typeof AuthenticatedAdminWorkflowsRoute
  AuthenticatedSettingsCatalogueRoute: typeof AuthenticatedSettingsCatalogueRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsQuotationTemplateRoute: typeof AuthenticatedSettingsQuotationTemplateRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedWorkbenchIntakeRoute: typeof AuthenticatedWorkbenchIntakeRoute
  AuthenticatedWorkbenchPortfolioRoute: typeof AuthenticatedWorkbenchPortfolioRoute
  AuthenticatedWorkbenchPricingRoute: typeof AuthenticatedWorkbenchPricingRoute
  AuthenticatedWorkbenchRequirementsRoute: typeof AuthenticatedWorkbenchRequirementsRoute
  AuthenticatedWorkbenchReviewRoute: typeof AuthenticatedWorkbenchReviewRoute
  AuthenticatedWorkbenchSourcingRoute: typeof AuthenticatedWorkbenchSourcingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminWorkflowsRoute: AuthenticatedAdminWorkflowsRoute,
  AuthenticatedSettingsCatalogueRoute: AuthenticatedSettingsCatalogueRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsQuotationTemplateRoute:
    AuthenticatedSettingsQuotationTemplateRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedWorkbenchIntakeRoute: AuthenticatedWorkbenchIntakeRoute,
  AuthenticatedWorkbenchPortfolioRoute: AuthenticatedWorkbenchPortfolioRoute,
  AuthenticatedWorkbenchPricingRoute: AuthenticatedWorkbenchPricingRoute,
  AuthenticatedWorkbenchRequirementsRoute:
    AuthenticatedWorkbenchRequirementsRoute,
  AuthenticatedWorkbenchReviewRoute: AuthenticatedWorkbenchReviewRoute,
  AuthenticatedWorkbenchSourcingRoute: AuthenticatedWorkbenchSourcingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
